# SPDX-FileCopyrightText: 2017-2022 Contributors to the OpenSTEF project <openstef@lfenergy.org> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0
# config of action in ./workflows/...
feature: ['feature*', 'feat*']
fix: ['fix*','bugfix*','hotfix*', 'bug*']
chore: ['chore*', 'doc*']
